;fyyre
;
import dsetup,\
       DirectXDeviceDriverSetup,'DirectXDeviceDriverSetupA',\
       DirectXLoadString,'DirectXLoadString',\
       DirectXRegisterApplication,'DirectXRegisterApplicationA',\
       DirectXSetup,'DirectXSetupA',\
       DirectXSetupCallback,'DirectXSetupCallback',\
       DirectXSetupGetEULA,'DirectXSetupGetEULAA',\
       DirectXSetupGetFileVersion,'DirectXSetupGetFileVersion',\
       DirectXSetupIsJapanNec,'DirectXSetupIsJapanNec',\
       DirectXSetupIsEng,'DirectXSetupIsEng',\
       DirectXSetupIsJapan,'DirectXSetupIsJapan',\
       DirectXSetupGetVersion,'DirectXSetupGetVersion',\
       DirectXSetupSetCallback,'DirectXSetupSetCallback',\
       DirectXSetupShowEUL,'DirectXSetupShowEULA',\
       DirectXUnRegisterApplication,'DirectXUnRegisterApplication'
