#include "stdafx.h"
#include "../L2_versions.h"
#include "L2PacketNames.h"

char l2_packet_names_server_t23[256][128];
char l2_packet_names_server2_t23[256][128];

void L2PacketNames_InitServer_t23()
{
	memset( l2_packet_names_server_t23, 0, sizeof(l2_packet_names_server_t23) );
	memset( l2_packet_names_server2_t23, 0, sizeof(l2_packet_names_server2_t23) );

	strcpy( l2_packet_names_server_t23[0], "Die" ); // 0
	strcpy( l2_packet_names_server_t23[1], "Revive" ); // 1
	strcpy( l2_packet_names_server_t23[2], "AttackOutofRange" ); // 2
	strcpy( l2_packet_names_server_t23[3], "AttackinCoolTime" ); // 3
	strcpy( l2_packet_names_server_t23[4], "AttackDeadTarget" ); // 4
	strcpy( l2_packet_names_server_t23[5], "SpawnItem" ); // 5
	strcpy( l2_packet_names_server_t23[6], "SellList" ); // 6
	strcpy( l2_packet_names_server_t23[7], "BuyList" ); // 7
	strcpy( l2_packet_names_server_t23[8], "DeleteObject" ); // 8
	strcpy( l2_packet_names_server_t23[9], "CharacterSelectionInfo" ); // 9
	strcpy( l2_packet_names_server_t23[10], "LoginFail" ); // a
	strcpy( l2_packet_names_server_t23[11], "CharSelected" ); // b
	strcpy( l2_packet_names_server_t23[12], "NpcInfo" ); // c
	strcpy( l2_packet_names_server_t23[13], "NewCharacterSuccess" ); // d
	strcpy( l2_packet_names_server_t23[14], "NewCharacterFail" ); // e
	strcpy( l2_packet_names_server_t23[15], "CharacterCreateSuccess" ); // f
	strcpy( l2_packet_names_server_t23[16], "CharacterCreateFail" ); // 10
	strcpy( l2_packet_names_server_t23[17], "ItemList" ); // 11
	strcpy( l2_packet_names_server_t23[18], "SunRise" ); // 12
	strcpy( l2_packet_names_server_t23[19], "SunSet" ); // 13
	strcpy( l2_packet_names_server_t23[20], "TradeStart" ); // 14
	strcpy( l2_packet_names_server_t23[21], "TradeStartOk" ); // 15
	strcpy( l2_packet_names_server_t23[22], "DropItem" ); // 16
	strcpy( l2_packet_names_server_t23[23], "GetItem" ); // 17
	strcpy( l2_packet_names_server_t23[24], "StatusUpdate" ); // 18
	strcpy( l2_packet_names_server_t23[25], "NpcHtmlMessage" ); // 19
	strcpy( l2_packet_names_server_t23[26], "TradeOwnAdd" ); // 1a
	strcpy( l2_packet_names_server_t23[27], "TradeOtherAdd" ); // 1b
	strcpy( l2_packet_names_server_t23[28], "TradeDone" ); // 1c
	strcpy( l2_packet_names_server_t23[29], "CharacterDeleteSuccess" ); // 1d
	strcpy( l2_packet_names_server_t23[30], "CharacterDeleteFail" ); // 1e
	strcpy( l2_packet_names_server_t23[31], "ActionFail" ); // 1f
	strcpy( l2_packet_names_server_t23[32], "SeverClose" ); // 20
	strcpy( l2_packet_names_server_t23[33], "InventoryUpdate" ); // 21
	strcpy( l2_packet_names_server_t23[34], "TeleportToLocation" ); // 22
	strcpy( l2_packet_names_server_t23[35], "TargetSelected" ); // 23
	strcpy( l2_packet_names_server_t23[36], "TargetUnselected" ); // 24
	strcpy( l2_packet_names_server_t23[37], "AutoAttackStart" ); // 25
	strcpy( l2_packet_names_server_t23[38], "AutoAttackStop" ); // 26
	strcpy( l2_packet_names_server_t23[39], "SocialAction" ); // 27
	strcpy( l2_packet_names_server_t23[40], "ChangeMoveType" ); // 28
	strcpy( l2_packet_names_server_t23[41], "ChangeWaitType" ); // 29
	strcpy( l2_packet_names_server_t23[42], "ManagePledgePower" ); // 2a
	strcpy( l2_packet_names_server_t23[43], "CreatePledge" ); // 2b
	strcpy( l2_packet_names_server_t23[44], "AskJoinPledge" ); // 2c
	strcpy( l2_packet_names_server_t23[45], "JoinPledge" ); // 2d
	strcpy( l2_packet_names_server_t23[46], "KeyPacket" ); // 2e
	strcpy( l2_packet_names_server_t23[47], "MoveToLocation" ); // 2f
	strcpy( l2_packet_names_server_t23[48], "NpcSay" ); // 30
	strcpy( l2_packet_names_server_t23[49], "CharInfo" ); // 31
	strcpy( l2_packet_names_server_t23[50], "UserInfo" ); // 32
	strcpy( l2_packet_names_server_t23[51], "Attack" ); // 33
	strcpy( l2_packet_names_server_t23[52], "WithdrawalPledge" ); // 34
	strcpy( l2_packet_names_server_t23[53], "OustPledgeMember" ); // 35
	strcpy( l2_packet_names_server_t23[54], "SetOustPledgeMember" ); // 36
	strcpy( l2_packet_names_server_t23[55], "DismissPledge" ); // 37
	strcpy( l2_packet_names_server_t23[56], "SetDismissPledge" ); // 38
	strcpy( l2_packet_names_server_t23[57], "AskJoinParty" ); // 39
	strcpy( l2_packet_names_server_t23[58], "JoinParty" ); // 3a
	strcpy( l2_packet_names_server_t23[59], "WithdrawalParty" ); // 3b
	strcpy( l2_packet_names_server_t23[60], "OustPartyMember" ); // 3c
	strcpy( l2_packet_names_server_t23[61], "SetOustPartyMember" ); // 3d
	strcpy( l2_packet_names_server_t23[62], "DismissParty" ); // 3e
	strcpy( l2_packet_names_server_t23[63], "SetDismissParty" ); // 3f
	strcpy( l2_packet_names_server_t23[64], "MagicAndSkillList" ); // 40
	strcpy( l2_packet_names_server_t23[65], "WareHouseDepositList" ); // 41
	strcpy( l2_packet_names_server_t23[66], "WareHouseWithdrawList" ); // 42
	strcpy( l2_packet_names_server_t23[67], "WareHouseDone" ); // 43
	strcpy( l2_packet_names_server_t23[68], "ShortCutRegister" ); // 44
	strcpy( l2_packet_names_server_t23[69], "ShortCutInit" ); // 45
	strcpy( l2_packet_names_server_t23[70], "ShortCutDelete" ); // 46
	strcpy( l2_packet_names_server_t23[71], "StopMove" ); // 47
	strcpy( l2_packet_names_server_t23[72], "MagicSkillUse" ); // 48
	strcpy( l2_packet_names_server_t23[73], "MagicSkillCanceled" ); // 49
	strcpy( l2_packet_names_server_t23[74], "SayPacket2" ); // 4a
	strcpy( l2_packet_names_server_t23[75], "EquipUpdate" ); // 4b
	strcpy( l2_packet_names_server_t23[76], "DoorInfo" ); // 4c
	strcpy( l2_packet_names_server_t23[77], "DoorStatusUpdate" ); // 4d
	strcpy( l2_packet_names_server_t23[78], "PartySmallWindowAll" ); // 4e
	strcpy( l2_packet_names_server_t23[79], "PartySmallWindowAdd" ); // 4f
	strcpy( l2_packet_names_server_t23[80], "PartySmallWindowDeleteAll" ); // 50
	strcpy( l2_packet_names_server_t23[81], "PartySmallWindowDelete" ); // 51
	strcpy( l2_packet_names_server_t23[82], "PartySmallWindowUpdate" ); // 52
	strcpy( l2_packet_names_server_t23[83], "TradePressOwnOk" ); // 53
	strcpy( l2_packet_names_server_t23[84], "MagicSkillLaunched" ); // 54
	strcpy( l2_packet_names_server_t23[85], "FriendAddRequestResult" ); // 55
	strcpy( l2_packet_names_server_t23[86], "FriendAdd" ); // 56
	strcpy( l2_packet_names_server_t23[87], "FriendRemove" ); // 57
	strcpy( l2_packet_names_server_t23[88], "FriendList" ); // 58
	strcpy( l2_packet_names_server_t23[89], "FriendStatus" ); // 59
	strcpy( l2_packet_names_server_t23[90], "PledgeShowMemberListAll" ); // 5a
	strcpy( l2_packet_names_server_t23[91], "PledgeShowMemberListUpdate" ); // 5b
	strcpy( l2_packet_names_server_t23[92], "PledgeShowMemberListAdd" ); // 5c
	strcpy( l2_packet_names_server_t23[93], "PledgeShowMemberListDelete" ); // 5d
	strcpy( l2_packet_names_server_t23[94], "MagicList" ); // 5e
	strcpy( l2_packet_names_server_t23[95], "SkillList" ); // 5f
	strcpy( l2_packet_names_server_t23[96], "VehicleInfo" ); // 60
	strcpy( l2_packet_names_server_t23[97], "FinishRotating" ); // 61
	strcpy( l2_packet_names_server_t23[98], "SystemMessage" ); // 62
	strcpy( l2_packet_names_server_t23[99], "StartPledgeWar" ); // 63
	strcpy( l2_packet_names_server_t23[100], "ReplyStartPledgeWar" ); // 64
	strcpy( l2_packet_names_server_t23[101], "StopPledgeWar" ); // 65
	strcpy( l2_packet_names_server_t23[102], "ReplyStopPledgeWar" ); // 66
	strcpy( l2_packet_names_server_t23[103], "SurrenderPledgeWar" ); // 67
	strcpy( l2_packet_names_server_t23[104], "ReplySurrenderPledgeWar" ); // 68
	strcpy( l2_packet_names_server_t23[105], "SetPledgeCrest" ); // 69
	strcpy( l2_packet_names_server_t23[106], "PledgeCrest" ); // 6a
	strcpy( l2_packet_names_server_t23[107], "SetupGauge" ); // 6b
	strcpy( l2_packet_names_server_t23[108], "VehicleDeparture" ); // 6c
	strcpy( l2_packet_names_server_t23[109], "VehicleCheckLocation" ); // 6d
	strcpy( l2_packet_names_server_t23[110], "GetOnVehicle" ); // 6e
	strcpy( l2_packet_names_server_t23[111], "GetOffVehicle" ); // 6f
	strcpy( l2_packet_names_server_t23[112], "TradeRequest" ); // 70
	strcpy( l2_packet_names_server_t23[113], "RestartResponse" ); // 71
	strcpy( l2_packet_names_server_t23[114], "MoveToPawn" ); // 72
	strcpy( l2_packet_names_server_t23[115], "SSQInfo" ); // 73
	strcpy( l2_packet_names_server_t23[116], "GameGuardQuery" ); // 74
	strcpy( l2_packet_names_server_t23[117], "L2FriendList" ); // 75
	strcpy( l2_packet_names_server_t23[118], "L2Friend" ); // 76
	strcpy( l2_packet_names_server_t23[119], "L2FriendStatus" ); // 77
	strcpy( l2_packet_names_server_t23[120], "L2FriendSay" ); // 78
	strcpy( l2_packet_names_server_t23[121], "ValidateLocation" ); // 79
	strcpy( l2_packet_names_server_t23[122], "StartRotating" ); // 7a
	strcpy( l2_packet_names_server_t23[123], "ShowBoard" ); // 7b
	strcpy( l2_packet_names_server_t23[124], "ChooseInventoryItem" ); // 7c
	strcpy( l2_packet_names_server_t23[125], "Dummy" ); // 7d
	strcpy( l2_packet_names_server_t23[126], "MoveToLocationInVehicle" ); // 7e
	strcpy( l2_packet_names_server_t23[127], "StopMoveInVehicle" ); // 7f
	strcpy( l2_packet_names_server_t23[128], "ValidateLocationInVehicle" ); // 80
	strcpy( l2_packet_names_server_t23[129], "TradeUpdate" ); // 81
	strcpy( l2_packet_names_server_t23[130], "TradePressOtherOk" ); // 82
	strcpy( l2_packet_names_server_t23[131], "FriendAddRequest" ); // 83
	strcpy( l2_packet_names_server_t23[132], "LogOutOk" ); // 84
	strcpy( l2_packet_names_server_t23[133], "AbnormalStatusUpdate" ); // 85
	strcpy( l2_packet_names_server_t23[134], "QuestList" ); // 86
	strcpy( l2_packet_names_server_t23[135], "EnchantResult" ); // 87
	strcpy( l2_packet_names_server_t23[136], "PledgeShowMemberListDeleteAll" ); // 88
	strcpy( l2_packet_names_server_t23[137], "PledgeInfo" ); // 89
	strcpy( l2_packet_names_server_t23[138], "PledgeExtendedInfo" ); // 8a
	strcpy( l2_packet_names_server_t23[139], "SurrenderPersonally" ); // 8b
	strcpy( l2_packet_names_server_t23[140], "Ride" ); // 8c
	strcpy( l2_packet_names_server_t23[141], "Dummy" ); // 8d
	strcpy( l2_packet_names_server_t23[142], "PledgeShowInfoUpdate" ); // 8e
	strcpy( l2_packet_names_server_t23[143], "ClientAction" ); // 8f
	strcpy( l2_packet_names_server_t23[144], "AcquireSkillList" ); // 90
	strcpy( l2_packet_names_server_t23[145], "AcquireSkillInfo" ); // 91
	strcpy( l2_packet_names_server_t23[146], "ServerObjectInfo" ); // 92
	strcpy( l2_packet_names_server_t23[147], "GMHide" ); // 93
	strcpy( l2_packet_names_server_t23[148], "AcquireSkillDone" ); // 94
	strcpy( l2_packet_names_server_t23[149], "GMViewCharacterInfo" ); // 95
	strcpy( l2_packet_names_server_t23[150], "GMViewPledgeInfo" ); // 96
	strcpy( l2_packet_names_server_t23[151], "GMViewSkillInfo" ); // 97
	strcpy( l2_packet_names_server_t23[152], "GMViewMagicInfo" ); // 98
	strcpy( l2_packet_names_server_t23[153], "GMViewQuestInfo" ); // 99
	strcpy( l2_packet_names_server_t23[154], "GMViewItemList" ); // 9a
	strcpy( l2_packet_names_server_t23[155], "GMViewWarehouseWithdrawList" ); // 9b
	strcpy( l2_packet_names_server_t23[156], "ListPartyWating" ); // 9c
	strcpy( l2_packet_names_server_t23[157], "PartyRoomInfo" ); // 9d
	strcpy( l2_packet_names_server_t23[158], "PlaySound" ); // 9e
	strcpy( l2_packet_names_server_t23[159], "StaticObject" ); // 9f
	strcpy( l2_packet_names_server_t23[160], "PrivateStoreManageList" ); // a0
	strcpy( l2_packet_names_server_t23[161], "PrivateStoreList" ); // a1
	strcpy( l2_packet_names_server_t23[162], "PrivateStoreMsg" ); // a2
	strcpy( l2_packet_names_server_t23[163], "ShowMinimap" ); // a3
	strcpy( l2_packet_names_server_t23[164], "ReviveRequest" ); // a4
	strcpy( l2_packet_names_server_t23[165], "AbnormalVisualEffect" ); // a5
	strcpy( l2_packet_names_server_t23[166], "TutorialShowHtml" ); // a6
	strcpy( l2_packet_names_server_t23[167], "TutorialShowQuestionMark" ); // a7
	strcpy( l2_packet_names_server_t23[168], "TutorialEnableClientEvent" ); // a8
	strcpy( l2_packet_names_server_t23[169], "TutorialCloseHtml" ); // a9
	strcpy( l2_packet_names_server_t23[170], "ShowRadar" ); // aa
	strcpy( l2_packet_names_server_t23[171], "WithdrawAlliance" ); // ab
	strcpy( l2_packet_names_server_t23[172], "OustAllianceMemberPledge" ); // ac
	strcpy( l2_packet_names_server_t23[173], "DismissAlliance" ); // ad
	strcpy( l2_packet_names_server_t23[174], "SetAllianceCrest" ); // ae
	strcpy( l2_packet_names_server_t23[175], "AllianceCrest" ); // af
	strcpy( l2_packet_names_server_t23[176], "ServerCloseSocket" ); // b0
	strcpy( l2_packet_names_server_t23[177], "PetStatusShow" ); // b1
	strcpy( l2_packet_names_server_t23[178], "PetInfo" ); // b2
	strcpy( l2_packet_names_server_t23[179], "PetItemList" ); // b3
	strcpy( l2_packet_names_server_t23[180], "PetInventoryUpdate" ); // b4
	strcpy( l2_packet_names_server_t23[181], "AllianceInfo" ); // b5
	strcpy( l2_packet_names_server_t23[182], "PetStatusUpdate" ); // b6
	strcpy( l2_packet_names_server_t23[183], "PetDelete" ); // b7
	strcpy( l2_packet_names_server_t23[184], "DeleteRadar" ); // b8
	strcpy( l2_packet_names_server_t23[185], "MyTargetSelected" ); // b9
	strcpy( l2_packet_names_server_t23[186], "PartyMemberPosition" ); // ba
	strcpy( l2_packet_names_server_t23[187], "AskJoinAlliance" ); // bb
	strcpy( l2_packet_names_server_t23[188], "JoinAlliance" ); // bc
	strcpy( l2_packet_names_server_t23[189], "PrivateStoreBuyManageList" ); // bd
	strcpy( l2_packet_names_server_t23[190], "PrivateStoreBuyList" ); // be
	strcpy( l2_packet_names_server_t23[191], "PrivateStoreBuyMsg" ); // bf
	strcpy( l2_packet_names_server_t23[192], "VehicleStart" ); // c0
	strcpy( l2_packet_names_server_t23[193], "RequestTimeCheck" ); // c1
	strcpy( l2_packet_names_server_t23[194], "StartAllianceWar" ); // c2
	strcpy( l2_packet_names_server_t23[195], "ReplyStartAllianceWar" ); // c3
	strcpy( l2_packet_names_server_t23[196], "StopAllianceWar" ); // c4
	strcpy( l2_packet_names_server_t23[197], "ReplyStopAllianceWar" ); // c5
	strcpy( l2_packet_names_server_t23[198], "SurrenderAllianceWar" ); // c6
	strcpy( l2_packet_names_server_t23[199], "SkillCoolTime" ); // c7
	strcpy( l2_packet_names_server_t23[200], "PackageToList" ); // c8
	strcpy( l2_packet_names_server_t23[201], "CastleSiegeInfo" ); // c9
	strcpy( l2_packet_names_server_t23[202], "CastleSiegeAttackerList" ); // ca
	strcpy( l2_packet_names_server_t23[203], "CastleSiegeDefenderList" ); // cb
	strcpy( l2_packet_names_server_t23[204], "NickNameChanged" ); // cc
	strcpy( l2_packet_names_server_t23[205], "PledgeStatusChanged" ); // cd
	strcpy( l2_packet_names_server_t23[206], "RelationChanged" ); // ce
	strcpy( l2_packet_names_server_t23[207], "EventTrigger" ); // cf
	strcpy( l2_packet_names_server_t23[208], "MultiSellList" ); // d0
	strcpy( l2_packet_names_server_t23[209], "SetSummonRemainTime" ); // d1
	strcpy( l2_packet_names_server_t23[210], "PackageSendableList" ); // d2
	strcpy( l2_packet_names_server_t23[211], "EarthQuake" ); // d3
	strcpy( l2_packet_names_server_t23[212], "FlyToLoaction" ); // d4
	strcpy( l2_packet_names_server_t23[213], "BlockList" ); // d5
	strcpy( l2_packet_names_server_t23[214], "SpecialCamera" ); // d6
	strcpy( l2_packet_names_server_t23[215], "NormalCamera" ); // d7
	strcpy( l2_packet_names_server_t23[216], "SkillRemainSec" ); // d8
	strcpy( l2_packet_names_server_t23[217], "NetPing" ); // d9
	strcpy( l2_packet_names_server_t23[218], "Dice" ); // da
	strcpy( l2_packet_names_server_t23[219], "Snoop" ); // db
	strcpy( l2_packet_names_server_t23[220], "RecipeBookItemList" ); // dc
	strcpy( l2_packet_names_server_t23[221], "RecipeItemMakeInfo" ); // dd
	strcpy( l2_packet_names_server_t23[222], "RecipeShopManageList" ); // de
	strcpy( l2_packet_names_server_t23[223], "RecipeShopSellList" ); // df
	strcpy( l2_packet_names_server_t23[224], "RecipeShopItemInfo" ); // e0
	strcpy( l2_packet_names_server_t23[225], "RecipeShopMsg" ); // e1
	strcpy( l2_packet_names_server_t23[226], "ShowCalc" ); // e2
	strcpy( l2_packet_names_server_t23[227], "MonRaceInfo" ); // e3
	strcpy( l2_packet_names_server_t23[228], "HennaItemInfo" ); // e4
	strcpy( l2_packet_names_server_t23[229], "HennaInfo" ); // e5
	strcpy( l2_packet_names_server_t23[230], "HennaUnequipList" ); // e6
	strcpy( l2_packet_names_server_t23[231], "HennaUnequipInfo" ); // e7
	strcpy( l2_packet_names_server_t23[232], "MacroList" ); // e8
	strcpy( l2_packet_names_server_t23[233], "BuyListSeed" ); // e9
	strcpy( l2_packet_names_server_t23[234], "ShowTownMap" ); // ea
	strcpy( l2_packet_names_server_t23[235], "ObserverStart" ); // eb
	strcpy( l2_packet_names_server_t23[236], "ObserverEnd" ); // ec
	strcpy( l2_packet_names_server_t23[237], "ChairSit" ); // ed
	strcpy( l2_packet_names_server_t23[238], "HennaEquipList" ); // ee
	strcpy( l2_packet_names_server_t23[239], "SellListProcure" ); // ef
	strcpy( l2_packet_names_server_t23[240], "GMHennaInfo" ); // f0
	strcpy( l2_packet_names_server_t23[241], "RadarControl" ); // f1
	strcpy( l2_packet_names_server_t23[242], "ClientSetTime" ); // f2
	strcpy( l2_packet_names_server_t23[243], "ConfirmDlg" ); // f3
	strcpy( l2_packet_names_server_t23[244], "PartySpelled" ); // f4
	strcpy( l2_packet_names_server_t23[245], "ShopPreviewList" ); // f5
	strcpy( l2_packet_names_server_t23[246], "ShopPreviewInfo" ); // f6
	strcpy( l2_packet_names_server_t23[247], "CameraMode" ); // f7
	strcpy( l2_packet_names_server_t23[248], "ShowXMasSeal" ); // f8
	strcpy( l2_packet_names_server_t23[249], "EtcStatusUpdate" ); // f9
	strcpy( l2_packet_names_server_t23[250], "ShortBuffStatusUpdate" ); // fa
	strcpy( l2_packet_names_server_t23[251], "SSQStatus" ); // fb
	strcpy( l2_packet_names_server_t23[252], "PetitionVote" ); // fc
	strcpy( l2_packet_names_server_t23[253], "AgitDecoInfo" ); // fd
	strcpy( l2_packet_names_server_t23[254], "Dummy" ); // fe

	// Double byte opcodes FE:xx
	strcpy( l2_packet_names_server2_t23[0], "ExDummy" ); // FE:0
	strcpy( l2_packet_names_server2_t23[1], "ExRegenMax" ); // FE:1
	strcpy( l2_packet_names_server2_t23[2], "ExEventMatchUserInfo" ); // FE:2
	strcpy( l2_packet_names_server2_t23[3], "ExColosseumFenceInfo" ); // FE:3
	strcpy( l2_packet_names_server2_t23[4], "ExEventMatchSpelledInfo" ); // FE:4
	strcpy( l2_packet_names_server2_t23[5], "ExEventMatchFirecracker" ); // FE:5
	strcpy( l2_packet_names_server2_t23[6], "ExEventMatchTeamUnlocked" ); // FE:6
	strcpy( l2_packet_names_server2_t23[7], "ExEventMatchGMTest" ); // FE:7
	strcpy( l2_packet_names_server2_t23[8], "ExPartyRoomMember" ); // FE:8
	strcpy( l2_packet_names_server2_t23[9], "ExClosePartyRoom" ); // FE:9
	strcpy( l2_packet_names_server2_t23[10], "ExManagePartyRoomMember" ); // FE:a
	strcpy( l2_packet_names_server2_t23[11], "ExEventMatchLockResult" ); // FE:b
	strcpy( l2_packet_names_server2_t23[12], "ExAutoSoulShot" ); // FE:c
	strcpy( l2_packet_names_server2_t23[13], "ExEventMatchList" ); // FE:d
	strcpy( l2_packet_names_server2_t23[14], "ExEventMatchObserver" ); // FE:e
	strcpy( l2_packet_names_server2_t23[15], "ExEventMatchMessage" ); // FE:f
	strcpy( l2_packet_names_server2_t23[16], "ExEventMatchScore" ); // FE:10
	strcpy( l2_packet_names_server2_t23[17], "ExServerPrimitive" ); // FE:11
	strcpy( l2_packet_names_server2_t23[18], "ExOpenMPCC" ); // FE:12
	strcpy( l2_packet_names_server2_t23[19], "ExCloseMPCC" ); // FE:13
	strcpy( l2_packet_names_server2_t23[20], "ExShowCastleInfo" ); // FE:14
	strcpy( l2_packet_names_server2_t23[21], "ExShowFortressInfo" ); // FE:15
	strcpy( l2_packet_names_server2_t23[22], "ExShowAgitInfo" ); // FE:16
	strcpy( l2_packet_names_server2_t23[23], "ExShowFortressSiegeInfo" ); // FE:17
	strcpy( l2_packet_names_server2_t23[24], "ExPartyPetWindowAdd" ); // FE:18
	strcpy( l2_packet_names_server2_t23[25], "ExPartyPetWindowUpdate" ); // FE:19
	strcpy( l2_packet_names_server2_t23[26], "ExAskJoinMPCC" ); // FE:1a
	strcpy( l2_packet_names_server2_t23[27], "ExPledgeCrestLarge" ); // FE:1b
	strcpy( l2_packet_names_server2_t23[28], "ExEventMatchTeamInfo" ); // FE:1c
	strcpy( l2_packet_names_server2_t23[29], "ExEventMatchCreate" ); // FE:1d
	strcpy( l2_packet_names_server2_t23[30], "ExFishingStart" ); // FE:1e
	strcpy( l2_packet_names_server2_t23[31], "ExFishingEnd" ); // FE:1f
	strcpy( l2_packet_names_server2_t23[32], "ExShowQuestInfo" ); // FE:20
	strcpy( l2_packet_names_server2_t23[33], "ExShowQuestMark" ); // FE:21
	strcpy( l2_packet_names_server2_t23[34], "ExSendManorList" ); // FE:22
	strcpy( l2_packet_names_server2_t23[35], "ExShowSeedInfo" ); // FE:23
	strcpy( l2_packet_names_server2_t23[36], "ExShowCropInfo" ); // FE:24
	strcpy( l2_packet_names_server2_t23[37], "ExShowManorDefaultInfo" ); // FE:25
	strcpy( l2_packet_names_server2_t23[38], "ExShowSeedSetting" ); // FE:26
	strcpy( l2_packet_names_server2_t23[39], "ExFishingStartCombat" ); // FE:27
	strcpy( l2_packet_names_server2_t23[40], "ExFishingHpRegen" ); // FE:28
	strcpy( l2_packet_names_server2_t23[41], "ExEnchantSkillList" ); // FE:29
	strcpy( l2_packet_names_server2_t23[42], "ExEnchantSkillInfo" ); // FE:2a
	strcpy( l2_packet_names_server2_t23[43], "ExShowCropSetting" ); // FE:2b
	strcpy( l2_packet_names_server2_t23[44], "ExShowSellCropList" ); // FE:2c
	strcpy( l2_packet_names_server2_t23[45], "ExOlympiadMatchEnd" ); // FE:2d
	strcpy( l2_packet_names_server2_t23[46], "ExMailArrived" ); // FE:2e
	strcpy( l2_packet_names_server2_t23[47], "ExStorageMaxCount" ); // FE:2f
	strcpy( l2_packet_names_server2_t23[48], "ExEventMatchManage" ); // FE:30
	strcpy( l2_packet_names_server2_t23[49], "ExMultiPartyCommandChannelInfo" ); // FE:31
	strcpy( l2_packet_names_server2_t23[50], "ExPCCafePointInfo" ); // FE:32
	strcpy( l2_packet_names_server2_t23[51], "ExSetCompassZoneCode" ); // FE:33
	strcpy( l2_packet_names_server2_t23[52], "ExGetBossRecord" ); // FE:34
	strcpy( l2_packet_names_server2_t23[53], "ExAskJoinPartyRoom" ); // FE:35
	strcpy( l2_packet_names_server2_t23[54], "ExListPartyMatchingWaitingRoom" ); // FE:36
	strcpy( l2_packet_names_server2_t23[55], "ExSetMpccRouting" ); // FE:37
	strcpy( l2_packet_names_server2_t23[56], "ExShowAdventurerGuideBook" ); // FE:38
	strcpy( l2_packet_names_server2_t23[57], "ExShowScreenMessage" ); // FE:39
	strcpy( l2_packet_names_server2_t23[58], "PledgeSkillList" ); // FE:3a
	strcpy( l2_packet_names_server2_t23[59], "PledgeSkillListAdd" ); // FE:3b
	strcpy( l2_packet_names_server2_t23[60], "PledgePowerGradeList" ); // FE:3c
	strcpy( l2_packet_names_server2_t23[61], "PledgeReceivePowerInfo" ); // FE:3d
	strcpy( l2_packet_names_server2_t23[62], "PledgeReceiveMemberInfo" ); // FE:3e
	strcpy( l2_packet_names_server2_t23[63], "PledgeReceiveWarList" ); // FE:3f
	strcpy( l2_packet_names_server2_t23[64], "PledgeReceiveSubPledgeCreated" ); // FE:40
	strcpy( l2_packet_names_server2_t23[65], "ExRedSky" ); // FE:41
	strcpy( l2_packet_names_server2_t23[66], "PledgeReceiveUpdatePower" ); // FE:42
	strcpy( l2_packet_names_server2_t23[67], "FlySelfDestination" ); // FE:43
	strcpy( l2_packet_names_server2_t23[68], "ShowPCCafeCouponShowUI" ); // FE:44
	strcpy( l2_packet_names_server2_t23[69], "ExSearchOrc" ); // FE:45
	strcpy( l2_packet_names_server2_t23[70], "ExCursedWeaponList" ); // FE:46
	strcpy( l2_packet_names_server2_t23[71], "ExCursedWeaponLocation" ); // FE:47
	strcpy( l2_packet_names_server2_t23[72], "ExRestartClient" ); // FE:48
	strcpy( l2_packet_names_server2_t23[73], "ExRequestHackShield" ); // FE:49
	strcpy( l2_packet_names_server2_t23[74], "ExUseSharedGroupItem" ); // FE:4a
	strcpy( l2_packet_names_server2_t23[75], "ExMPCCShowPartyMemberInfo" ); // FE:4b
	strcpy( l2_packet_names_server2_t23[76], "ExDuelAskStart" ); // FE:4c
	strcpy( l2_packet_names_server2_t23[77], "ExDuelReady" ); // FE:4d
	strcpy( l2_packet_names_server2_t23[78], "ExDuelStart" ); // FE:4e
	strcpy( l2_packet_names_server2_t23[79], "ExDuelEnd" ); // FE:4f
	strcpy( l2_packet_names_server2_t23[80], "ExDuelUpdateUserInfo" ); // FE:50
	strcpy( l2_packet_names_server2_t23[81], "ExShowVariationMakeWindow" ); // FE:51
	strcpy( l2_packet_names_server2_t23[82], "ExShowVariationCancelWindow" ); // FE:52
	strcpy( l2_packet_names_server2_t23[83], "ExPutItemResultForVariationMake" ); // FE:53
	strcpy( l2_packet_names_server2_t23[84], "ExPutIntensiveResultForVariationMake" ); // FE:54
	strcpy( l2_packet_names_server2_t23[85], "ExPutCommissionResultForVariationMake" ); // FE:55
	strcpy( l2_packet_names_server2_t23[86], "ExVariationResult" ); // FE:56
	strcpy( l2_packet_names_server2_t23[87], "ExPutItemResultForVariationCancel" ); // FE:57
	strcpy( l2_packet_names_server2_t23[88], "ExVariationCancelResult" ); // FE:58
	strcpy( l2_packet_names_server2_t23[89], "ExDuelEnemyRelation" ); // FE:59
	strcpy( l2_packet_names_server2_t23[90], "ExPlayAnimation" ); // FE:5a
	strcpy( l2_packet_names_server2_t23[91], "ExMPCCPartyInfoUpdate" ); // FE:5b
	strcpy( l2_packet_names_server2_t23[92], "ExPlayScene" ); // FE:5c
	strcpy( l2_packet_names_server2_t23[93], "ExSpawnEmitter" ); // FE:5d
	strcpy( l2_packet_names_server2_t23[94], "ExEnchantSkillInfoDetail" ); // FE:5e
	strcpy( l2_packet_names_server2_t23[95], "ExBasicActionList" ); // FE:5f
	strcpy( l2_packet_names_server2_t23[96], "ExAirShipInfo" ); // FE:60
	strcpy( l2_packet_names_server2_t23[97], "ExAttributeEnchantResult" ); // FE:61
	strcpy( l2_packet_names_server2_t23[98], "ExChooseInventoryAttributeItem" ); // FE:62
	strcpy( l2_packet_names_server2_t23[99], "ExGetOnAirShip" ); // FE:63
	strcpy( l2_packet_names_server2_t23[100], "ExGetOffAirShip" ); // FE:64
	strcpy( l2_packet_names_server2_t23[101], "ExMoveToLocationAirShip" ); // FE:65
	strcpy( l2_packet_names_server2_t23[102], "ExStopMoveAirShip" ); // FE:66
	strcpy( l2_packet_names_server2_t23[103], "ExShowTrace" ); // FE:67
	strcpy( l2_packet_names_server2_t23[104], "ExItemAuctionInfo" ); // FE:68
	strcpy( l2_packet_names_server2_t23[105], "ExNeedToChangeName" ); // FE:69
	strcpy( l2_packet_names_server2_t23[106], "ExPartyPetWindowDelete" ); // FE:6a
	strcpy( l2_packet_names_server2_t23[107], "ExTutorialList" ); // FE:6b
	strcpy( l2_packet_names_server2_t23[108], "ExRpItemLink" ); // FE:6c
	strcpy( l2_packet_names_server2_t23[109], "ExMoveToLocationInAirShip" ); // FE:6d
	strcpy( l2_packet_names_server2_t23[110], "ExStopMoveInAirShip" ); // FE:6e
	strcpy( l2_packet_names_server2_t23[111], "ExValidateLocationInAirShip" ); // FE:6f
	strcpy( l2_packet_names_server2_t23[112], "ExUISetting" ); // FE:70
	strcpy( l2_packet_names_server2_t23[113], "ExMoveToTargetInAirShip" ); // FE:71
	strcpy( l2_packet_names_server2_t23[114], "ExAttackInAirShip" ); // FE:72
	strcpy( l2_packet_names_server2_t23[115], "ExMagicSkillUseInAirShip" ); // FE:73
	strcpy( l2_packet_names_server2_t23[116], "ExShowBaseAttributeCancelWindow" ); // FE:74
	strcpy( l2_packet_names_server2_t23[117], "ExBaseAttributeCancelResult" ); // FE:75
	strcpy( l2_packet_names_server2_t23[118], "ExSubPledgetSkillAdd" ); // FE:76
	strcpy( l2_packet_names_server2_t23[119], "ExResponseFreeServer" ); // FE:77
	strcpy( l2_packet_names_server2_t23[120], "ExShowProcureCropDetail" ); // FE:78
	strcpy( l2_packet_names_server2_t23[121], "ExHeroList" ); // FE:79
	strcpy( l2_packet_names_server2_t23[122], "ExOlympiadUserInfo" ); // FE:7a
	strcpy( l2_packet_names_server2_t23[123], "ExOlympiadSpelledInfo" ); // FE:7b
	strcpy( l2_packet_names_server2_t23[124], "ExOlympiadMode" ); // FE:7c
	strcpy( l2_packet_names_server2_t23[125], "ExShowFortressMapInfo" ); // FE:7d
	strcpy( l2_packet_names_server2_t23[126], "ExPVPMatchRecord" ); // FE:7e
	strcpy( l2_packet_names_server2_t23[127], "ExPVPMatchUserDie" ); // FE:7f
	strcpy( l2_packet_names_server2_t23[128], "ExPrivateStoreWholeMsg" ); // FE:80
	strcpy( l2_packet_names_server2_t23[129], "ExPutEnchantTargetItemResult" ); // FE:81
	strcpy( l2_packet_names_server2_t23[130], "ExPutEnchantSupportItemResult" ); // FE:82
	strcpy( l2_packet_names_server2_t23[131], "ExChangeNicknameNColor" ); // FE:83
	strcpy( l2_packet_names_server2_t23[132], "ExGetBookMarkInfo" ); // FE:84
	strcpy( l2_packet_names_server2_t23[133], "ExNotifyPremiumItem" ); // FE:85
	strcpy( l2_packet_names_server2_t23[134], "ExGetPremiumItemList" ); // FE:86
	strcpy( l2_packet_names_server2_t23[135], "ExPeriodicItemList" ); // FE:87
	strcpy( l2_packet_names_server2_t23[136], "ExJumpToLocation" ); // FE:88
	strcpy( l2_packet_names_server2_t23[137], "ExPVPMatchCCRecord" ); // FE:89
	strcpy( l2_packet_names_server2_t23[138], "ExPVPMatchCCMyRecord" ); // FE:8a
	strcpy( l2_packet_names_server2_t23[139], "ExPVPMatchCCRetire" ); // FE:8b
	strcpy( l2_packet_names_server2_t23[140], "ExShowTerritory" ); // FE:8c
	strcpy( l2_packet_names_server2_t23[141], "ExNpcQuestHtmlMessage" ); // FE:8d
	strcpy( l2_packet_names_server2_t23[142], "ExSendUIEvent" ); // FE:8e
	strcpy( l2_packet_names_server2_t23[143], "ExNotifyBirthDay" ); // FE:8f
	strcpy( l2_packet_names_server2_t23[144], "ExShowDominionRegistry" ); // FE:90
	strcpy( l2_packet_names_server2_t23[145], "ExReplyRegisterDominion" ); // FE:91
	strcpy( l2_packet_names_server2_t23[146], "ExReplyDominionInfo" ); // FE:92
	strcpy( l2_packet_names_server2_t23[147], "ExShowOwnthingPos" ); // FE:93
	strcpy( l2_packet_names_server2_t23[148], "ExCleftList" ); // FE:94
	strcpy( l2_packet_names_server2_t23[149], "ExCleftState" ); // FE:95
	strcpy( l2_packet_names_server2_t23[150], "ExDominionChannelSet" ); // FE:96
	strcpy( l2_packet_names_server2_t23[151], "ExBlockUpSetList" ); // FE:97
	strcpy( l2_packet_names_server2_t23[152], "ExBlockUpSetState" ); // FE:98
	strcpy( l2_packet_names_server2_t23[153], "ExStartScenePlayer" ); // FE:99
	strcpy( l2_packet_names_server2_t23[154], "ExAirShipTeleportList" ); // FE:9a
	strcpy( l2_packet_names_server2_t23[155], "ExMpccRoomInfo" ); // FE:9b
	strcpy( l2_packet_names_server2_t23[156], "ExListMpccWaiting" ); // FE:9c
	strcpy( l2_packet_names_server2_t23[157], "ExDissmissMpccRoom" ); // FE:9d
	strcpy( l2_packet_names_server2_t23[158], "ExManageMpccRoomMember" ); // FE:9e
	strcpy( l2_packet_names_server2_t23[159], "ExMpccRoomMember" ); // FE:9f
	strcpy( l2_packet_names_server2_t23[160], "ExVitalityPointInfo" ); // FE:a0
	strcpy( l2_packet_names_server2_t23[161], "ExShowSeedMapInfo" ); // FE:a1
	strcpy( l2_packet_names_server2_t23[162], "ExMpccPartymasterList" ); // FE:a2
	strcpy( l2_packet_names_server2_t23[163], "ExDominionWarStart" ); // FE:a3
	strcpy( l2_packet_names_server2_t23[164], "ExDominionWarEnd" ); // FE:a4
	strcpy( l2_packet_names_server2_t23[165], "ExDummy" ); // FE:a5
	strcpy( l2_packet_names_server2_t23[166], "ExBR_GamePoint" ); // FE:a6
	strcpy( l2_packet_names_server2_t23[167], "ExBR_ProductList" ); // FE:a7
	strcpy( l2_packet_names_server2_t23[168], "ExBR_ProductInfo" ); // FE:a8
	strcpy( l2_packet_names_server2_t23[169], "ExBR_BuyProduct" ); // FE:a9
	strcpy( l2_packet_names_server2_t23[170], "ExBR_PremiumState" ); // FE:aa
	strcpy( l2_packet_names_server2_t23[171], "ExBrBroadcastEventState" ); // FE:ab
	strcpy( l2_packet_names_server2_t23[172], "ExBrExtraUserInfo" ); // FE:ac
	strcpy( l2_packet_names_server2_t23[183], "ExBuySellListPacket (Epilogue)" ); // FE:B7
	strcpy( l2_packet_names_server2_t23[190], "ExBrExtraUserInfo (Epilogue)" ); // FE:BE (chdd)
}

void L2Packets_GetL2PacketName_fromServer_t23(
	unsigned char opcode1,
	unsigned short opcode2,
	char *outPacketName,
	unsigned int cchMax )
{
	if( opcode1 != 0xFE )
	{
		strncpy( outPacketName, l2_packet_names_server_t23[opcode1], cchMax );
	}
	else
	{
		strncpy( outPacketName, l2_packet_names_server2_t23[opcode2], cchMax );
	}
}

