#include "stdafx.h"
#include "../L2_versions.h"
#include "L2PacketNames.h"

char l2_packet_names_server[256][128];
char l2_packet_names_server2[256][128];

void L2PacketNames_InitServer()
{
	strcpy( l2_packet_names_server[0], "Die" );
	strcpy( l2_packet_names_server[1], "Revive" );
	l2_packet_names_server[2][0] = 0;
	l2_packet_names_server[3][0] = 0;
	l2_packet_names_server[4][0] = 0;
	strcpy( l2_packet_names_server[5], "SpawnItem" );
	strcpy( l2_packet_names_server[6], "SellList" );
	strcpy( l2_packet_names_server[7], "BuyList" );
	strcpy( l2_packet_names_server[8], "DeleteObject" );
	strcpy( l2_packet_names_server[9], "CharSelectionInfo" );
	strcpy( l2_packet_names_server[10], "LoginFail" );
	strcpy( l2_packet_names_server[11], "CharSelected" );
	strcpy( l2_packet_names_server[12], "NpcInfo" );
	strcpy( l2_packet_names_server[13], "NewCharacterSuccess" );
	strcpy( l2_packet_names_server[14], "ObservationReturn" );
	strcpy( l2_packet_names_server[15], "CharCreateOk" );
	strcpy( l2_packet_names_server[16], "CharCreateFail" );
	strcpy( l2_packet_names_server[17], "ItemList" );
	strcpy( l2_packet_names_server[18], "SunRise" );
	strcpy( l2_packet_names_server[19], "SunSet" );
	strcpy( l2_packet_names_server[20], "TradeStart" );
	l2_packet_names_server[21][0] = 0;
	strcpy( l2_packet_names_server[22], "DropItem" );
	strcpy( l2_packet_names_server[23], "GetItem" );
	strcpy( l2_packet_names_server[24], "StatusUpdate" );
	strcpy( l2_packet_names_server[25], "NpcHtmlMessage" );
	strcpy( l2_packet_names_server[26], "TradeOwnAdd" );
	strcpy( l2_packet_names_server[27], "TradeOtherAdd" );
	strcpy( l2_packet_names_server[28], "TradeDone" );
	strcpy( l2_packet_names_server[29], "CharDeleteSuccess" );
	strcpy( l2_packet_names_server[30], "CharDeleteFail" );
	strcpy( l2_packet_names_server[31], "ActionFailed" );
	strcpy( l2_packet_names_server[32], "ServerClose" );
	strcpy( l2_packet_names_server[33], "InventoryUpdate" );
	strcpy( l2_packet_names_server[34], "TeleportToLocation" );
	strcpy( l2_packet_names_server[35], "TargetSelected" );
	strcpy( l2_packet_names_server[36], "TargetUnselected" );
	strcpy( l2_packet_names_server[37], "AutoAttackStart" );
	strcpy( l2_packet_names_server[38], "AutoAttackStop" );
	strcpy( l2_packet_names_server[39], "SocialAction" );
	strcpy( l2_packet_names_server[40], "ChangeMoveType" );
	strcpy( l2_packet_names_server[41], "ChangeWaitType" );
	strcpy( l2_packet_names_server[42], "ManagePledgePower" );
	l2_packet_names_server[43][0] = 0;
	strcpy( l2_packet_names_server[44], "AskJoinPledge" );
	strcpy( l2_packet_names_server[45], "JoinPledge" );
	strcpy( l2_packet_names_server[46], "KeyPacket" );
	strcpy( l2_packet_names_server[47], "MoveToLocation" );
	strcpy( l2_packet_names_server[48], "NpcSay" );
	strcpy( l2_packet_names_server[49], "CharInfo" );
	strcpy( l2_packet_names_server[50], "UserInfo" );
	strcpy( l2_packet_names_server[51], "Attack" );
	l2_packet_names_server[52][0] = 0;
	l2_packet_names_server[53][0] = 0;
	l2_packet_names_server[54][0] = 0;
	l2_packet_names_server[55][0] = 0;
	l2_packet_names_server[56][0] = 0;
	strcpy( l2_packet_names_server[57], "AskJoinParty" );
	strcpy( l2_packet_names_server[58], "JoinParty" );
	l2_packet_names_server[59][0] = 0;
	l2_packet_names_server[60][0] = 0;
	l2_packet_names_server[61][0] = 0;
	l2_packet_names_server[62][0] = 0;
	l2_packet_names_server[63][0] = 0;
	l2_packet_names_server[64][0] = 0;
	strcpy( l2_packet_names_server[65], "WareHouseDepositList" );
	strcpy( l2_packet_names_server[66], "WareHouseWithdrawalList" );
	l2_packet_names_server[67][0] = 0;
	strcpy( l2_packet_names_server[68], "ShortCutRegister" );
	strcpy( l2_packet_names_server[69], "ShortCutInit" );
	l2_packet_names_server[70][0] = 0;
	strcpy( l2_packet_names_server[71], "StopMove" );
	strcpy( l2_packet_names_server[72], "MagicSkillUse" );
	strcpy( l2_packet_names_server[73], "MagicSkillCanceld" );
	strcpy( l2_packet_names_server[74], "CreatureSay" );
	strcpy( l2_packet_names_server[75], "EquipUpdate" );
	strcpy( l2_packet_names_server[76], "DoorInfo" );
	strcpy( l2_packet_names_server[77], "DoorStatusUpdate" );
	strcpy( l2_packet_names_server[78], "PartySmallWindowAll" );
	strcpy( l2_packet_names_server[79], "PartySmallWindowAdd" );
	strcpy( l2_packet_names_server[80], "PartySmallWindowDeleteAll" );
	strcpy( l2_packet_names_server[81], "PartySmallWindowDelete" );
	strcpy( l2_packet_names_server[82], "PartySmallWindowUpdate" );
	l2_packet_names_server[83][0] = 0;
	strcpy( l2_packet_names_server[84], "MagicSkillLaunched" );
	l2_packet_names_server[85][0] = 0;
	l2_packet_names_server[86][0] = 0;
	l2_packet_names_server[87][0] = 0;
	l2_packet_names_server[88][0] = 0;
	l2_packet_names_server[89][0] = 0;
	strcpy( l2_packet_names_server[90], "PledgeShowMemberListAll" );
	strcpy( l2_packet_names_server[91], "PledgeShowMemberListUpdate" );
	strcpy( l2_packet_names_server[92], "PledgeShowMemberListAdd" );
	strcpy( l2_packet_names_server[93], "PledgeShowMemberListDelete" );
	l2_packet_names_server[94][0] = 0;
	strcpy( l2_packet_names_server[95], "SkillList" );
	strcpy( l2_packet_names_server[96], "VehicleInfo" );
	strcpy( l2_packet_names_server[97], "StopRotation" );
	strcpy( l2_packet_names_server[98], "SystemMessage" );
	strcpy( l2_packet_names_server[99], "StartPledgeWar" );
	l2_packet_names_server[100][0] = 0;
	strcpy( l2_packet_names_server[101], "StopPledgeWar" );
	l2_packet_names_server[102][0] = 0;
	strcpy( l2_packet_names_server[103], "SurrenderPledgeWar" );
	l2_packet_names_server[104][0] = 0;
	l2_packet_names_server[105][0] = 0;
	strcpy( l2_packet_names_server[106], "PledgeCrest" );
	strcpy( l2_packet_names_server[107], "SetupGauge" );
	strcpy( l2_packet_names_server[108], "VehicleDeparture" );
	strcpy( l2_packet_names_server[109], "VehicleCheckLocation" );
	strcpy( l2_packet_names_server[110], "GetOnVehicle" );
	strcpy( l2_packet_names_server[111], "GetOffVehicle" );
	strcpy( l2_packet_names_server[112], "SendTradeRequest" );
	strcpy( l2_packet_names_server[113], "RestartResponse" );
	strcpy( l2_packet_names_server[114], "MoveToPawn" );
	strcpy( l2_packet_names_server[115], "SSQInfo" );
	strcpy( l2_packet_names_server[116], "GameGuardQuery" );
	strcpy( l2_packet_names_server[117], "FriendList" );
	l2_packet_names_server[118][0] = 0;
	l2_packet_names_server[119][0] = 0;
	strcpy( l2_packet_names_server[120], "L2FriendSay" );
	strcpy( l2_packet_names_server[121], "ValidateLocation" );
	strcpy( l2_packet_names_server[122], "StartRotation" );
	strcpy( l2_packet_names_server[123], "ShowBoard" );
	strcpy( l2_packet_names_server[124], "ChooseInventoryItem" );
	l2_packet_names_server[125][0] = 0;
	strcpy( l2_packet_names_server[126], "MoveToLocationInVehicle" );
	strcpy( l2_packet_names_server[127], "StopMoveInVehicle" );
	strcpy( l2_packet_names_server[128], "ValidateLocationInVehicle" );
	l2_packet_names_server[129][0] = 0;
	l2_packet_names_server[130][0] = 0;
	strcpy( l2_packet_names_server[131], "FriendAddRequest" );
	strcpy( l2_packet_names_server[132], "LeaveWorld" );
	strcpy( l2_packet_names_server[133], "AbnormalStatusUpdate" );
	strcpy( l2_packet_names_server[134], "QuestList" );
	strcpy( l2_packet_names_server[135], "ExPutEnchantTargetItemResult/EnchantResult?" );
	strcpy( l2_packet_names_server[136], "PledgeShowMemberListDeleteAll" );
	strcpy( l2_packet_names_server[137], "PledgeInfo" );
	l2_packet_names_server[138][0] = 0;
	l2_packet_names_server[139][0] = 0;
	strcpy( l2_packet_names_server[140], "Ride" );
	l2_packet_names_server[141][0] = 0;
	strcpy( l2_packet_names_server[142], "PledgeShowInfoUpdate" );
	l2_packet_names_server[143][0] = 0;
	strcpy( l2_packet_names_server[144], "AcquireSkillList" );
	strcpy( l2_packet_names_server[145], "AcquireSkillInfo" );
	l2_packet_names_server[146][0] = 0;
	strcpy( l2_packet_names_server[147], "GMHide" );
	strcpy( l2_packet_names_server[148], "AcquireSkillDone" );
	strcpy( l2_packet_names_server[149], "GMViewCharacterInfo" );
	strcpy( l2_packet_names_server[150], "GMViewPledgeInfo" );
	strcpy( l2_packet_names_server[151], "GMViewSkillInfo" );
	l2_packet_names_server[152][0] = 0;
	strcpy( l2_packet_names_server[153], "GmViewQuestInfo" );
	strcpy( l2_packet_names_server[154], "GMViewItemList" );
	strcpy( l2_packet_names_server[155], "GMViewWarehouseWithdrawList" );
	strcpy( l2_packet_names_server[156], "ListPartyWating" );
	strcpy( l2_packet_names_server[157], "PartyMatchDetail" );
	strcpy( l2_packet_names_server[158], "PlaySound" );
	strcpy( l2_packet_names_server[159], "StaticObject" );
	strcpy( l2_packet_names_server[160], "PrivateStoreManageListSell" );
	strcpy( l2_packet_names_server[161], "PrivateStoreListSell" );
	strcpy( l2_packet_names_server[162], "PrivateStoreMsgSell" );
	strcpy( l2_packet_names_server[163], "ShowMiniMap" );
	l2_packet_names_server[164][0] = 0;
	l2_packet_names_server[165][0] = 0;
	strcpy( l2_packet_names_server[166], "TutorialShowHtml" );
	strcpy( l2_packet_names_server[167], "TutorialShowQuestionMark" );
	strcpy( l2_packet_names_server[168], "TutorialEnableClientEvent" );
	strcpy( l2_packet_names_server[169], "TutorialCloseHtml" );
	l2_packet_names_server[170][0] = 0;
	l2_packet_names_server[171][0] = 0;
	l2_packet_names_server[172][0] = 0;
	l2_packet_names_server[173][0] = 0;
	l2_packet_names_server[174][0] = 0;
	strcpy( l2_packet_names_server[175], "AllyCrest" );
	l2_packet_names_server[176][0] = 0;
	strcpy( l2_packet_names_server[177], "PetStatusShow" );
	strcpy( l2_packet_names_server[178], "PetInfo" );
	strcpy( l2_packet_names_server[179], "PetItemList" );
	strcpy( l2_packet_names_server[180], "PetInventoryUpdate" );
	l2_packet_names_server[181][0] = 0;
	strcpy( l2_packet_names_server[182], "PetStatusUpdate" );
	strcpy( l2_packet_names_server[183], "PetDelete" );
	l2_packet_names_server[184][0] = 0;
	strcpy( l2_packet_names_server[185], "MyTargetSelected" );
	strcpy( l2_packet_names_server[186], "PartyMemberPosition" );
	strcpy( l2_packet_names_server[187], "AskJoinAlly" );
	l2_packet_names_server[188][0] = 0;
	strcpy( l2_packet_names_server[189], "PrivateStoreManageListBuy" );
	strcpy( l2_packet_names_server[190], "PrivateStoreListBuy" );
	strcpy( l2_packet_names_server[191], "PrivateStoreMsgBuy" );
	strcpy( l2_packet_names_server[192], "VehicleStarted" );
	l2_packet_names_server[193][0] = 0;
	l2_packet_names_server[194][0] = 0;
	l2_packet_names_server[195][0] = 0;
	l2_packet_names_server[196][0] = 0;
	l2_packet_names_server[197][0] = 0;
	l2_packet_names_server[198][0] = 0;
	strcpy( l2_packet_names_server[199], "SkillCoolTime" );
	strcpy( l2_packet_names_server[200], "PackageToList" );
	strcpy( l2_packet_names_server[201], "SiegeInfo" );
	strcpy( l2_packet_names_server[202], "SiegeAttackerList" );
	strcpy( l2_packet_names_server[203], "SiegeDefenderList" );
	strcpy( l2_packet_names_server[204], "NicknameChanged" );
	strcpy( l2_packet_names_server[205], "PledgeStatusChanged" );
	strcpy( l2_packet_names_server[206], "RelationChanged" );
	l2_packet_names_server[207][0] = 0;
	strcpy( l2_packet_names_server[208], "MultiSellList" );
	strcpy( l2_packet_names_server[209], "SetSummonRemainTime" );
	strcpy( l2_packet_names_server[210], "PackageSendableList" );
	strcpy( l2_packet_names_server[211], "Earthquake" );
	strcpy( l2_packet_names_server[212], "FlyToLocation" );
	l2_packet_names_server[213][0] = 0;
	strcpy( l2_packet_names_server[214], "SpecialCamera" );
	strcpy( l2_packet_names_server[215], "NormalCamera" );
	l2_packet_names_server[216][0] = 0;
	l2_packet_names_server[217][0] = 0;
	strcpy( l2_packet_names_server[218], "Dice" );
	strcpy( l2_packet_names_server[219], "Snoop" );
	strcpy( l2_packet_names_server[220], "RecipeBookItemList" );
	strcpy( l2_packet_names_server[221], "RecipeItemMakeInfo" );
	strcpy( l2_packet_names_server[222], "RecipeShopManageList" );
	strcpy( l2_packet_names_server[223], "RecipeShopSellList" );
	strcpy( l2_packet_names_server[224], "RecipeShopItemInfo" );
	strcpy( l2_packet_names_server[225], "RecipeShopMsg" );
	strcpy( l2_packet_names_server[226], "ShowCalculator" );
	strcpy( l2_packet_names_server[227], "MonRaceInfo" );
	strcpy( l2_packet_names_server[228], "HennaItemInfo" );
	strcpy( l2_packet_names_server[229], "HennaInfo" );
	l2_packet_names_server[230][0] = 0;
	l2_packet_names_server[231][0] = 0;
	strcpy( l2_packet_names_server[232], "SendMacroList" );
	strcpy( l2_packet_names_server[233], "BuyListSeed" );
	strcpy( l2_packet_names_server[234], "ShowTownMap" );
	strcpy( l2_packet_names_server[235], "ObservationMode" );
	l2_packet_names_server[236][0] = 0;
	strcpy( l2_packet_names_server[237], "ChairSit" );
	strcpy( l2_packet_names_server[238], "HennaEquipList" );
	strcpy( l2_packet_names_server[239], "SellListProcure" );
	strcpy( l2_packet_names_server[240], "GMHennaInfo" );
	strcpy( l2_packet_names_server[241], "RadarControl" );
	strcpy( l2_packet_names_server[242], "ClientSetTime" );
	strcpy( l2_packet_names_server[243], "ConfirmDlg" );
	strcpy( l2_packet_names_server[244], "PartySpelled" );
	strcpy( l2_packet_names_server[245], "ShopPreviewList" );
	l2_packet_names_server[246][0] = 0;
	strcpy( l2_packet_names_server[247], "CameraMode" );
	strcpy( l2_packet_names_server[248], "ShowXMasSeal" );
	strcpy( l2_packet_names_server[249], "EtcStatusUpdate" );
	strcpy( l2_packet_names_server[250], "ShortBuffStatusUpdate" );
	strcpy( l2_packet_names_server[251], "SSQStatus" );
	l2_packet_names_server[252][0] = 0;
	strcpy( l2_packet_names_server[253], "AgitDecoInfo" );
	l2_packet_names_server[254][0] = 0;
	l2_packet_names_server[255][0] = 0;
	// double-opcode
	l2_packet_names_server2[0][0] = 0;
	strcpy( l2_packet_names_server2[1], "ExRegMax" );
	l2_packet_names_server2[2][0] = 0;
	l2_packet_names_server2[3][0] = 0;
	l2_packet_names_server2[4][0] = 0;
	l2_packet_names_server2[5][0] = 0;
	l2_packet_names_server2[6][0] = 0;
	l2_packet_names_server2[7][0] = 0;
	l2_packet_names_server2[8][0] = 0;
	l2_packet_names_server2[9][0] = 0;
	l2_packet_names_server2[10][0] = 0;
	l2_packet_names_server2[11][0] = 0;
	strcpy( l2_packet_names_server2[12], "ExAutoSoulShot" );
	l2_packet_names_server2[13][0] = 0;
	l2_packet_names_server2[14][0] = 0;
	l2_packet_names_server2[15][0] = 0;
	l2_packet_names_server2[16][0] = 0;
	l2_packet_names_server2[17][0] = 0;
	strcpy( l2_packet_names_server2[18], "ExOpenMPCC" );
	strcpy( l2_packet_names_server2[19], "ExCloseMPCC" );
	strcpy( l2_packet_names_server2[20], "ExShowCastleInfo" );
	strcpy( l2_packet_names_server2[21], "ExShowFortressInfo" );
	strcpy( l2_packet_names_server2[22], "ExShowAgitInfo" );
	strcpy( l2_packet_names_server2[23], "ExShowFortressSiegeInfo" );
	strcpy( l2_packet_names_server2[24], "ExPartyPetWindowAdd" );
	strcpy( l2_packet_names_server2[25], "ExPartyPetWindowUpdate" );
	strcpy( l2_packet_names_server2[26], "ExAskJoinMPCC" );
	strcpy( l2_packet_names_server2[27], "ExPledgeCrestLarge" );
	l2_packet_names_server2[28][0] = 0;
	l2_packet_names_server2[29][0] = 0;
	strcpy( l2_packet_names_server2[30], "ExFishingStart" );
	strcpy( l2_packet_names_server2[31], "ExFishingEnd" );
	strcpy( l2_packet_names_server2[32], "ExShowQuestInfo" );
	strcpy( l2_packet_names_server2[33], "ExShowQuestMark" );
	strcpy( l2_packet_names_server2[34], "ExSendManorList" );
	strcpy( l2_packet_names_server2[35], "ExShowSeedInfo" );
	strcpy( l2_packet_names_server2[36], "ExShowCropInfo" );
	strcpy( l2_packet_names_server2[37], "ExShowManorDefaultInfo" );
	strcpy( l2_packet_names_server2[38], "ExShowSeedSetting" );
	strcpy( l2_packet_names_server2[39], "ExFishingStartCombat" );
	strcpy( l2_packet_names_server2[40], "ExFishingHpRegen" );
	strcpy( l2_packet_names_server2[41], "ExEnchantSkillList" );
	strcpy( l2_packet_names_server2[42], "ExEnchantSkillInfo" );
	strcpy( l2_packet_names_server2[43], "ExShowCropSetting" );
	strcpy( l2_packet_names_server2[44], "ExShowSellCropList" );
	l2_packet_names_server2[45][0] = 0;
	strcpy( l2_packet_names_server2[46], "ExMailArrived" );
	strcpy( l2_packet_names_server2[47], "ExStorageMaxCount" );
	l2_packet_names_server2[48][0] = 0;
	strcpy( l2_packet_names_server2[49], "ExMultiPartyCommandChannelInfo" );
	strcpy( l2_packet_names_server2[50], "ExPCCafePointInfo" );
	strcpy( l2_packet_names_server2[51], "ExSetCompassZoneCode" );
	strcpy( l2_packet_names_server2[52], "ExGetBossRecord" );
	strcpy( l2_packet_names_server2[53], "ExAskJoinPartyRoom" );
	l2_packet_names_server2[54][0] = 0;
	l2_packet_names_server2[55][0] = 0;
	strcpy( l2_packet_names_server2[56], "ExShowAdventurerGuideBook" );
	strcpy( l2_packet_names_server2[57], "ExShowScreenMessage" );
	strcpy( l2_packet_names_server2[58], "PledgeSkillList" );
	strcpy( l2_packet_names_server2[59], "PledgeSkillListAdd" );
	strcpy( l2_packet_names_server2[60], "PledgePowerGradeList" );
	strcpy( l2_packet_names_server2[61], "PledgeReceivePowerInfo" );
	strcpy( l2_packet_names_server2[62], "PledgeReceiveMemberInfo" );
	strcpy( l2_packet_names_server2[63], "PledgeReceiveWarList" );
	strcpy( l2_packet_names_server2[64], "PledgeReceiveSubPledgeCreated" );
	strcpy( l2_packet_names_server2[65], "ExRedSky" );
	l2_packet_names_server2[66][0] = 0;
	l2_packet_names_server2[67][0] = 0;
	strcpy( l2_packet_names_server2[68], "ShowPCCafeCouponShowUI" );
	strcpy( l2_packet_names_server2[69], "ExSearchOrc" );
	strcpy( l2_packet_names_server2[70], "ExCursedWeaponList" );
	strcpy( l2_packet_names_server2[71], "ExCursedWeaponLocation" );
	strcpy( l2_packet_names_server2[72], "ExRestartClient" );
	strcpy( l2_packet_names_server2[73], "ExRequestHackShield" );
	strcpy( l2_packet_names_server2[74], "ExUseSharedGroupItem" );
	strcpy( l2_packet_names_server2[75], "ExMPCCShowPartyMemberInfo" );
	strcpy( l2_packet_names_server2[76], "ExDuelAskStart" );
	strcpy( l2_packet_names_server2[77], "ExDuelReady" );
	strcpy( l2_packet_names_server2[78], "ExDuelStart" );
	strcpy( l2_packet_names_server2[79], "ExDuelEnd" );
	strcpy( l2_packet_names_server2[80], "ExDuelUpdateUserInfo" );
	strcpy( l2_packet_names_server2[81], "ExShowVariationMakeWindow" );
	strcpy( l2_packet_names_server2[82], "ExShowVariationCancelWindow" );
	strcpy( l2_packet_names_server2[83], "ExPutItemResultForVariationMake" );
	strcpy( l2_packet_names_server2[84], "ExPutIntensiveResultForVariationMake" );
	strcpy( l2_packet_names_server2[85], "ExPutCommissionResultForVariationMake" );
	strcpy( l2_packet_names_server2[86], "ExVariationResult" );
	strcpy( l2_packet_names_server2[87], "ExPutItemResultForVariationCancel" );
	strcpy( l2_packet_names_server2[88], "ExVariationCancelResult" );
	l2_packet_names_server2[89][0] = 0;
	l2_packet_names_server2[90][0] = 0;
	strcpy( l2_packet_names_server2[91], "ExMPCCPartyInfoUpdate" );
	strcpy( l2_packet_names_server2[92], "ExPlayScene" );
	strcpy( l2_packet_names_server2[93], "ExSpawnEmitter" );
	strcpy( l2_packet_names_server2[94], "ExEnchantSkillInfoDetail" );
	strcpy( l2_packet_names_server2[95], "ExBasicActionList" );
	l2_packet_names_server2[96][0] = 0;
	strcpy( l2_packet_names_server2[97], "ExAttributeEnchantResult" );
	strcpy( l2_packet_names_server2[98], "ExChooseInventoryAttributeItem" );
	l2_packet_names_server2[99][0] = 0;
	l2_packet_names_server2[100][0] = 0;
	l2_packet_names_server2[101][0] = 0;
	l2_packet_names_server2[102][0] = 0;
	strcpy( l2_packet_names_server2[103], "ExShowTrace" );
	l2_packet_names_server2[104][0] = 0;
	l2_packet_names_server2[105][0] = 0;
	strcpy( l2_packet_names_server2[106], "ExPartyPetWindowDelete" );
	l2_packet_names_server2[107][0] = 0;
	strcpy( l2_packet_names_server2[108], "ExRpItemLink" );
	l2_packet_names_server2[109][0] = 0;
	l2_packet_names_server2[110][0] = 0;
	l2_packet_names_server2[111][0] = 0;
	strcpy( l2_packet_names_server2[112], "ExUISetting" ); // answer to RequestKeyMapping
	l2_packet_names_server2[113][0] = 0;
	l2_packet_names_server2[114][0] = 0;
	l2_packet_names_server2[115][0] = 0;
	l2_packet_names_server2[116][0] = 0;
	l2_packet_names_server2[117][0] = 0;
	l2_packet_names_server2[118][0] = 0;
	l2_packet_names_server2[119][0] = 0;
	strcpy( l2_packet_names_server2[120], "ExShowProcureCropDetail" );
	strcpy( l2_packet_names_server2[121], "ExHeroList" );
	strcpy( l2_packet_names_server2[122], "ExOlympiadUserInfoSpectator" );
	strcpy( l2_packet_names_server2[123], "ExOlympiadSpelledInfo" );
	strcpy( l2_packet_names_server2[124], "ExOlympiadMode" );
	strcpy( l2_packet_names_server2[125], "ExShowFortressMapInfo" );
	l2_packet_names_server2[126][0] = 0;
	l2_packet_names_server2[127][0] = 0;
	strcpy( l2_packet_names_server2[128], "ExPrivateStoreSetWholeMsg" );
	strcpy( l2_packet_names_server2[129], "RequestEnchant" );
	l2_packet_names_server2[130][0] = 0;
	l2_packet_names_server2[131][0] = 0;
	l2_packet_names_server2[132][0] = 0;
	l2_packet_names_server2[133][0] = 0;
	l2_packet_names_server2[134][0] = 0;
	l2_packet_names_server2[135][0] = 0;
	l2_packet_names_server2[136][0] = 0;
	l2_packet_names_server2[137][0] = 0;
	l2_packet_names_server2[138][0] = 0;
	l2_packet_names_server2[139][0] = 0;
	l2_packet_names_server2[140][0] = 0;
	l2_packet_names_server2[141][0] = 0;
	l2_packet_names_server2[142][0] = 0;
	l2_packet_names_server2[143][0] = 0;
	l2_packet_names_server2[144][0] = 0;
	l2_packet_names_server2[145][0] = 0;
	l2_packet_names_server2[146][0] = 0;
	l2_packet_names_server2[147][0] = 0;
	l2_packet_names_server2[148][0] = 0;
	l2_packet_names_server2[149][0] = 0;
	l2_packet_names_server2[150][0] = 0;
	l2_packet_names_server2[151][0] = 0;
	l2_packet_names_server2[152][0] = 0;
	l2_packet_names_server2[153][0] = 0;
	l2_packet_names_server2[154][0] = 0;
	l2_packet_names_server2[155][0] = 0;
	l2_packet_names_server2[156][0] = 0;
	l2_packet_names_server2[157][0] = 0;
	l2_packet_names_server2[158][0] = 0;
	l2_packet_names_server2[159][0] = 0;
	l2_packet_names_server2[160][0] = 0;
	l2_packet_names_server2[161][0] = 0;
	l2_packet_names_server2[162][0] = 0;
	l2_packet_names_server2[163][0] = 0;
	l2_packet_names_server2[164][0] = 0;
	l2_packet_names_server2[165][0] = 0;
	l2_packet_names_server2[166][0] = 0;
	l2_packet_names_server2[167][0] = 0;
	l2_packet_names_server2[168][0] = 0;
	l2_packet_names_server2[169][0] = 0;
	l2_packet_names_server2[170][0] = 0;
	l2_packet_names_server2[171][0] = 0;
	l2_packet_names_server2[172][0] = 0;
	l2_packet_names_server2[173][0] = 0;
	l2_packet_names_server2[174][0] = 0;
	l2_packet_names_server2[175][0] = 0;
	l2_packet_names_server2[176][0] = 0;
	l2_packet_names_server2[177][0] = 0;
	l2_packet_names_server2[178][0] = 0;
	l2_packet_names_server2[179][0] = 0;
	l2_packet_names_server2[180][0] = 0;
	l2_packet_names_server2[181][0] = 0;
	l2_packet_names_server2[182][0] = 0;
	l2_packet_names_server2[183][0] = 0;
	l2_packet_names_server2[184][0] = 0;
	l2_packet_names_server2[185][0] = 0;
	l2_packet_names_server2[186][0] = 0;
	l2_packet_names_server2[187][0] = 0;
	l2_packet_names_server2[188][0] = 0;
	l2_packet_names_server2[189][0] = 0;
	l2_packet_names_server2[190][0] = 0;
	l2_packet_names_server2[191][0] = 0;
	l2_packet_names_server2[192][0] = 0;
	l2_packet_names_server2[193][0] = 0;
	l2_packet_names_server2[194][0] = 0;
	l2_packet_names_server2[195][0] = 0;
	l2_packet_names_server2[196][0] = 0;
	l2_packet_names_server2[197][0] = 0;
	l2_packet_names_server2[198][0] = 0;
	l2_packet_names_server2[199][0] = 0;
	l2_packet_names_server2[200][0] = 0;
	l2_packet_names_server2[201][0] = 0;
	l2_packet_names_server2[202][0] = 0;
	l2_packet_names_server2[203][0] = 0;
	l2_packet_names_server2[204][0] = 0;
	l2_packet_names_server2[205][0] = 0;
	l2_packet_names_server2[206][0] = 0;
	l2_packet_names_server2[207][0] = 0;
	l2_packet_names_server2[208][0] = 0;
	l2_packet_names_server2[209][0] = 0;
	l2_packet_names_server2[210][0] = 0;
	l2_packet_names_server2[211][0] = 0;
	l2_packet_names_server2[212][0] = 0;
	l2_packet_names_server2[213][0] = 0;
	l2_packet_names_server2[214][0] = 0;
	l2_packet_names_server2[215][0] = 0;
	l2_packet_names_server2[216][0] = 0;
	l2_packet_names_server2[217][0] = 0;
	l2_packet_names_server2[218][0] = 0;
	l2_packet_names_server2[219][0] = 0;
	l2_packet_names_server2[220][0] = 0;
	l2_packet_names_server2[221][0] = 0;
	l2_packet_names_server2[222][0] = 0;
	l2_packet_names_server2[223][0] = 0;
	l2_packet_names_server2[224][0] = 0;
	l2_packet_names_server2[225][0] = 0;
	l2_packet_names_server2[226][0] = 0;
	l2_packet_names_server2[227][0] = 0;
	l2_packet_names_server2[228][0] = 0;
	l2_packet_names_server2[229][0] = 0;
	l2_packet_names_server2[230][0] = 0;
	l2_packet_names_server2[231][0] = 0;
	l2_packet_names_server2[232][0] = 0;
	l2_packet_names_server2[233][0] = 0;
	l2_packet_names_server2[234][0] = 0;
	l2_packet_names_server2[235][0] = 0;
	l2_packet_names_server2[236][0] = 0;
	l2_packet_names_server2[237][0] = 0;
	l2_packet_names_server2[238][0] = 0;
	l2_packet_names_server2[239][0] = 0;
	l2_packet_names_server2[240][0] = 0;
	l2_packet_names_server2[241][0] = 0;
	l2_packet_names_server2[242][0] = 0;
	l2_packet_names_server2[243][0] = 0;
	l2_packet_names_server2[244][0] = 0;
	l2_packet_names_server2[245][0] = 0;
	l2_packet_names_server2[246][0] = 0;
	l2_packet_names_server2[247][0] = 0;
	l2_packet_names_server2[248][0] = 0;
	l2_packet_names_server2[249][0] = 0;
	l2_packet_names_server2[250][0] = 0;
	l2_packet_names_server2[251][0] = 0;
	l2_packet_names_server2[252][0] = 0;
	l2_packet_names_server2[253][0] = 0;
	l2_packet_names_server2[254][0] = 0;
	l2_packet_names_server2[255][0] = 0;
}

void L2Packets_GetL2PacketName_fromServer(
	unsigned char opcode1,
	unsigned short opcode2,
	char *outPacketName,
	unsigned int cchMax )
{
	if( opcode1 != 0xFE )
	{
		strncpy( outPacketName, l2_packet_names_server[opcode1], cchMax );
	}
	else
	{
		strncpy( outPacketName, l2_packet_names_server2[opcode2], cchMax );
	}
}
