#define IDC_MYICON                      2
#define IDD_L2OOGHELPER_DIALOG          102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_L2OOGHELPER                 107
#define IDI_SMALL                       108
#define IDC_L2OOGHELPER                 109
#define IDR_MAINFRAME                   128
#define IDD_ACCOUNT                     130
#define IDMENU_DEBUG                    131
#define IDD_TAB                         132
#define IDD_CHOOSESERVER                133
#define IDD_CHOOSECHAR                  134
#define IDD_USERINFO                    135
#define IDD_USERINV                     136
#define IDD_USERSKILLS                  137
#define IDD_USERBUFF                    138
#define IDD_MAPINFO                     139
#define IDD_MBTIMEOUT                   140
#define IDD_USERPARTY                   141
#define IDD_USERINV_ITEMCOUNT           142
#define IDD_USERINV_DROPITEM            143
#define IDD_NPCHTML                     144
#define IDD_BOTCONFIG                   145
#define IDD_BOTCFG_SELFHEAL             146
#define IDD_BOTCFG_PARTY                147
#define IDD_BOTCFG_SELF                 148
#define IDD_BOTCFG_SELFHEAL_COND        149
#define IDD_FINDINDB                    150
#define IDD_TRADEITEMS                  151
#define IDD_PRIVATETRADEITEMS           152
#define IDD_INPUTSTRING                 153
#define IDD_TRADEP2P                    154
#define IDD_CREATECHAR                  155

#define IDC_E_LOGIN                     1001
#define IDC_E_PASS                      1002
#define IDC_E_IP                        1003
#define IDC_E_PORT                      1004
#define IDC_C_GAME_MANUAL               1005
#define IDC_E_GSID                      1006
#define IDC_C_CHAR_MANUAL               1007
#define IDC_E_CHARNAME                  1008
#define IDC_CB_CONFIG                   1009
#define IDC_LOAD                        1010
#define IDC_SAVE                        1011
#define IDC_TAB_INFO                    1011
#define IDC_CB_L2VER                    1012
#define IDC_TAB_CHAT                    1013
#define IDC_PR_HP                       1014
#define IDC_ST_CHAR_NAME                1015
#define IDC_PR_MP                       1016
#define IDC_PR_CP                       1017
#define IDC_CHECK1                      1018
#define IDC_C_BOTENABLE                 1018
#define IDC_C_PARTY_AUTO_ACCEPT         1018
#define IDC_CHECK2                      1019
#define IDC_C_BOTCOMBATENABLE           1019
#define IDC_C_PARTY_AUTO_INVITE         1019
#define IDC_C_MAPSHOWMOBS               1020
#define IDC_C_STANDHP                   1020
#define IDC_C_MAPSHOWNPCS               1021
#define IDC_C_STANDMP                   1021
#define IDC_C_MAPSHOWPCS                1022
#define IDC_C_MAPSHOWITEMS              1023
#define IDC_C_MAPSHOWZONE               1024
#define IDC_E_MAPSHOWDZ                 1025
#define IDC_E_CHAT                      1027
#define IDC_B_SAY                       1028
#define IDC_B_SYSTEM                    1029
#define IDC_PR_WEIGHT                   1030
#define IDC_B_CLOSETAB                  1031
#define IDC_B_CONFIG                    1032
#define IDC_LIST1                       1033
#define IDC_PR_TARGETHP                 1033
#define IDC_E_PROTO                     1034
#define IDC_C_MAPSHOWVECTORS            1034
#define IDC_C_PROTOAUTO                 1035
#define IDC_PR_CASTING                  1035
#define IDC_SLI_SCALE                   1036
#define IDC_ST_EXP                      1037
#define IDC_ST_SP                       1038
#define IDC_ST_PATK                     1039
#define IDC_ST_PDEF                     1040
#define IDC_ST_ACCURACY                 1041
#define IDC_ST_CRITICAL                 1042
#define IDC_ST_MATK                     1043
#define IDC_ST_MDEF                     1044
#define IDC_ST_EVASION                  1045
#define IDC_ST_SPEED                    1046
#define IDC_ST_STR                      1047
#define IDC_ST_DEX                      1048
#define IDC_ST_CON                      1049
#define IDC_ST_INT                      1050
#define IDC_ST_WIT                      1051
#define IDC_ST_MEN                      1052
#define IDC_ST_KARMA                    1053
#define IDC_ST_PVPPK                    1054
#define IDC_ST_RECOM                    1055
#define IDC_ST_FAME                     1056
#define IDC_LISTITEMS                   1056
#define IDC_ST_ATKATTRIB                1057
#define IDC_DESTROY                     1057
#define IDC_ST_ATTRIBVAL                1058
#define IDC_DROP                        1058
#define IDC_ST_FIRE                     1059
#define IDC_LINKCHAT                    1059
#define IDC_ST_WATER                    1060
#define IDC_CRYSTALLIZE                 1060
#define IDC_ST_WIND                     1061
#define IDC_GIVETOPET                   1061
#define IDC_ST_EARTH                    1062
#define IDC_ST_INVSIZE                  1062
#define IDC_ST_HOLY                     1063
#define IDC_ST_DARK                     1064
#define IDC_ST_ATKSPD                   1065
#define IDC_TAB2                        1065
#define IDC_ST_CASTSPEED                1066
#define IDC_B_SCRIPT                    1066
#define IDC_CANCELBUFF                  1067
#define IDC_ST_VITALITYLEVEL            1067
#define IDC_ST_NBUFFS                   1068
#define IDC_B_DEBUG                     1069
#define IDC_PROGRESS1                   1070
#define IDC_ST_Q                        1071
#define IDC_EDITNAME                    1071
#define IDC_LEAVEPARTY                  1072
#define IDC_R_STWITH                    1072
#define IDC_CHANGEPARTYLEADER           1073
#define IDC_ST_TARGETNAME               1073
#define IDC_R_CONTAINS                  1073
#define IDC_KICKPARTYMEMBER             1074
#define IDC_R_ENWITH                    1074
#define IDC_MAPAREA                     1075
#define IDC_B_CANCELTARGET              1076
#define IDC_B_ATTACKTARGET              1077
#define IDC_FIND                        1077
#define IDC_B_SITSTAND                  1078
#define IDC_B_RUNWALK                   1079
#define IDC_ST_WAITTYPE                 1080
#define IDC_ST_ITEMNAME                 1081
#define IDC_B_ACTIONTARGET              1081
#define IDC_E_COUNT                     1082
#define IDC_B_ALL                       1083
#define IDC_B_2                         1084
#define IDC_B_1                         1085
#define IDC_PR_EXP                      1085
#define IDC_B_3                         1086
#define IDC_B_4                         1087
#define IDC_EDIT1                       1087
#define IDC_B_6                         1088
#define IDC_COMBO1                      1088
#define IDC_E_SITMP                     1088
#define IDC_B_5                         1089
#define IDC_E_STANDHP                   1089
#define IDC_CB_MP                       1089
#define IDC_B_7                         1090
#define IDC_EDIT2                       1090
#define IDC_E_STANDMP                   1090
#define IDC_B_9                         1091
#define IDC_ST_PARTYLEADER              1091
#define IDC_E_MP                        1091
#define IDC_B_8                         1092
#define IDC_ST_PARTYLOOTTYPE            1092
#define IDC_CB_CP                       1092
#define IDC_E_CP                        1093
#define IDC_C_MAPSHOWMAP                1094
#define IDC_TREE1                       1095
#define IDC_C_SITHP                     1097
#define IDC_C_SITMP                     1098
#define IDC_E_SITHP                     1099
#define IDC_APPLY                       1100
#define IDC_E_PARTY_AUTO_ACCEPT         1101
#define IDC_E_PARTY_AUTO_INVITE         1102
#define IDC_CB_PARTY_LOOT               1103
#define IDC_C_FOLLOW_ENABLE             1104
#define IDC_E_FOLLOW_NAME               1105
#define IDC_E_FOLLOW_DIST               1106
#define IDC_C_PARTY_ASSIST              1107
#define IDC_R_GENERAL                   1108
#define IDC_R_HEALER                    1109
#define IDC_R_NUKER                     1110
#define IDC_COMBO2                      1111
#define IDC_B_ADD                       1112
#define IDC_B_EDIT                      1113
#define IDC_B_FIND                      1113
#define IDC_B_DEL                       1114
#define IDC_DELAYMS                     1114
#define IDC_E_DELAYMS                   1114
#define IDC_E_ITEM                      1115
#define IDC_CB_HP                       1116
#define IDC_E_HP                        1117
#define IDC_E_ITEMID                    1118
#define IDC_CB_AI_MODEL                 1119
#define IDC_B_ACTIONS                   1120
#define IDC_LIST2                       1121
#define IDC_ST_UPPER                    1122
#define IDC_ST_DOWN                     1123
#define IDC_B_MSGSELL                   1124
#define IDC_QUESTION                    1125
#define IDC_C_MAPSHOWSELL               1126
#define IDC_C_MAPSHOWBUY                1127
#define IDC_C_MAPSHOWCRAFT              1128
#define IDC_LV_INV                      1129
#define IDC_LV_SEND                     1130
#define IDC_LV_RECV                     1131
#define IDC_ST_TRADECHAR                1132
#define IDC_CHARCREATE                  1133
#define IDC_CHARDEL                     1134
#define IDC_CHARLDELCANCEL              1135
#define IDC_CB_CLASS                    1136
#define IDC_CB_HSTYLE                   1137
#define IDC_CB_HCOLOR                   1138
#define IDC_CB_FSTYLE                   1139
#define IDC_CB_GENDER                   1140

#define IDM_LINEAGE_ADD_ACC             32772
#define ID_DEBUG_ENABLE                 32773
#define ID_DEBUG_ENABLE32774            32774
#define ID_DEBUG_ENABLECON              32775
#define ID_DEBUG_DISABLECON             32776
#define ID_DEBUG_LOGLEVEL               32777
#define ID_LOGLEVEL_LOG                 32778
#define ID_LOGLEVEL_LOG32779            32779
#define ID_LOGLEVEL_OK                  32780
#define ID_LOGLEVEL_WARN                32781
#define ID_LOGLEVEL_ERROR               32782
#define ID_LOGLEVEL_USERAI              32783
#define ID_LOGLEVEL_PACKETNAME          32784
#define ID_LOGLEVEL_DEBUG               32785
#define ID_LOGLEVEL_DEBUGDUMP           32786
#define ID_DEBUG_RUNTESTSCRIPT          32787
#define ID_DEBUG_DUMPCHARS              32788
#define ID_32789                        32789
#define IDC_STATIC                      -1
