proc DirectXDeviceDriverSetupA
    xor   eax, eax
    ret
endp

proc DirectXDeviceDriverSetupW
    xor   eax, eax
    ret
endp

proc DirectXRegisterApplicationA
    xor   eax, eax
    ret
endp
proc DirectXRegisterApplicationW
    xor   eax, eax
    ret
endp

proc DirectXSetupA
    xor   eax, eax
    ret
endp

proc DirectXSetupIsJapan
    xor   eax, eax
    ret
endp

proc DirectXSetupIsJapanNec
    xor   eax, eax
    ret
endp

proc DirectXSetupW
     xor  eax, eax
     ret
endp

proc DirectXUnRegisterApplication
     xor  eax, eax
     ret
endp

proc DirectXSetupSetCallback
     xor  eax, eax
     ret
endp

proc DirectXSetupGetVersion
    xor   eax, eax
    ret
endp

proc DirectXSetupCallback
    xor   eax, eax
    ret
endp

proc DirectXSetupGetFileVersion
    xor   eax, eax
    ret
endp

proc DirectXLoadString
    xor   eax, eax
    ret
endp

proc DirectXSetupIsEng
    xor   eax, eax
    ret
endp

proc DirectXSetupShowEULA
    xor   eax, eax
    ret
endp

proc DirectXSetupGetEULAA
    xor   eax, eax
    ret
endp

proc DirectXSetupGetEULAW
    xor   eax, eax
    ret
endp