#pragma once

enum GS_LoginFailReason
{
	REASON_IP_BANNED = 1,
	REASON_IP_RESERVED = 2,
	REASON_WRONG_HEXID = 3,
	REASON_ID_RESERVED = 4,
	REASON_NO_FREE_ID = 5,
	NOT_AUTHED = 6,
	REASON_ALREADY_LOGGED_IN = 7
};

enum GS_ServerListStatus
{
	SERVER_LIST_STATUS = 0x01,
	SERVER_LIST_CLOCK = 0x02,
	SERVER_LIST_SQUARE_BRACKET = 0x03,
	SERVER_LIST_MAX_PLAYERS = 0x04,
	SERVER_LIST_TEST_SERVER = 0x05
};

enum ServerStatus
{
	SERVER_STATUS_AUTO = 0x00,
	SERVER_STATUS_GOOD = 0x01,
	SERVER_STATUS_NORMAL = 0x02,
	SERVER_STATUS_FULL = 0x03,
	SERVER_STATUS_DOWN = 0x04,
	SERVER_STATUS_GM_ONLY = 0x05
};

enum ClientState
{
	CLIENT_STATE_OFFLINE = 0x00,
	CLIENT_STATE_CONNECTED = 0x01,
	CLIENT_STATE_AUTHED = 0x02,
	CLIENT_STATE_IN_GAME = 0x03
};
